# Generated by Django 4.1.3 on 2022-12-06 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0002_form_tb_proimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='form_tb',
            name='offprice',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
