# Generated by Django 4.1.3 on 2022-12-07 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0003_form_tb_offprice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form_tb',
            name='email',
        ),
        migrations.RemoveField(
            model_name='form_tb',
            name='password',
        ),
        migrations.AlterField(
            model_name='form_tb',
            name='proimage',
            field=models.ImageField(upload_to='forms/'),
        ),
    ]
