# Generated by Django 4.1.3 on 2022-12-08 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0004_remove_form_tb_email_remove_form_tb_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form_tb',
            name='details',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='form_tb',
            name='proimage',
            field=models.ImageField(upload_to='product/'),
        ),
    ]
