# Generated by Django 4.1.3 on 2022-12-02 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app5', '0002_rename_password2_signup_tb_hashpassword'),
    ]

    operations = [
        migrations.CreateModel(
            name='admin_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
    ]
