# Generated by Django 4.1.3 on 2022-12-02 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app5', '0003_admin_tb'),
    ]

    operations = [
        migrations.DeleteModel(
            name='admin_tb',
        ),
    ]
