# Generated by Django 4.1.3 on 2022-12-05 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app5', '0004_delete_admin_tb'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup_tb',
            name='message',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
