# Generated by Django 4.1.3 on 2022-12-05 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app5', '0005_signup_tb_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signup_tb',
            old_name='fname',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='signup_tb',
            name='lname',
        ),
    ]
