# Generated by Django 4.1.3 on 2022-12-06 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app5', '0006_rename_fname_signup_tb_name_remove_signup_tb_lname'),
    ]

    operations = [
        migrations.CreateModel(
            name='product_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.CharField(max_length=255)),
                ('offprice', models.CharField(max_length=255)),
                ('details', models.TextField()),
                ('proimage', models.ImageField(upload_to='product/')),
                ('category', models.CharField(max_length=255)),
            ],
        ),
    ]
