# Generated by Django 4.1.3 on 2022-12-12 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app5', '0008_cart_tb'),
    ]

    operations = [
        migrations.CreateModel(
            name='cont_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('subject', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('message', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='cart_tb',
        ),
        migrations.DeleteModel(
            name='product_tb',
        ),
        migrations.DeleteModel(
            name='signup_tb',
        ),
    ]
